# Generated by Django 4.2.7 on 2023-11-19 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coll_UnitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalUnits', models.IntegerField(default=0)),
                ('unitsNames', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rm_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CollegianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalCode', models.CharField(max_length=10)),
                ('collegianCode', models.CharField(max_length=14)),
                ('collegianFirstName', models.CharField(max_length=200)),
                ('collegianLastName', models.CharField(max_length=300)),
                ('collegianAge', models.IntegerField(default=18)),
                ('collegianFathersName', models.CharField(max_length=400)),
                ('collegianMajor', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rm_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('coll_units', models.ManyToManyField(to='register.coll_unitsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalCode', models.CharField(max_length=10)),
                ('professorCode', models.CharField(max_length=14)),
                ('professorFirstName', models.CharField(max_length=200)),
                ('professorLastName', models.CharField(max_length=300)),
                ('professorAge', models.IntegerField(default=28)),
                ('professorFathersName', models.CharField(max_length=400)),
                ('professorMajor', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rm_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('collegians', models.ManyToManyField(to='register.collegianmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Coll_Units',
        ),
        migrations.DeleteModel(
            name='Collegian',
        ),
        migrations.DeleteModel(
            name='Professors',
        ),
        migrations.AddField(
            model_name='coll_unitsmodel',
            name='professors',
            field=models.ManyToManyField(to='register.professorsmodel'),
        ),
    ]
